spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/hrmaz-realm
          jwk-set-uri: http://localhost:8088/realms/hrmaz-realm/protocol/openid-connect/certs
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # register: true
        # enabled: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        service-name: ${spring.application.name}
        ip-address: host.docker.internal
        prefer-ip-address: true

    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      - name: RequestRateLimiter
        args:
          key-resolver: '#{@ipKeyResolver}'
          redis-rate-limiter:
            replenishRate: 2
            burstCapacity: 10
            requestedTokens: 1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: 'http://localhost:4200'
            allowedMethods: 'GET, POST, PUT, DELETE, OPTIONS'
            allowedHeaders: '*'
            exposed-headers:
            - Authorization
            - Set-Cookie
            allowCredentials: true

    title: account micro service
    version: 1.0
    url:
      front-end: http://localhost:4200
    upload:
      day-off-document:
        max-size: 2_097_152  #2MB

server:
  port: 8080

logging:
  level:
    org: 
      springframework:
        cloud:
          gateway: INFO

security:
  jwt:
    secret: Ns6SpnvuJgwRCli/WbFpCIPhBkhjBTYxE4VORK/dxRQ=
    access-token-lifetime-milliseconds: 300_000
    issuer: hrm-system
    audience: hrm-audience

# otel:
#   exporter:
#     otlp:
#       endpoint: http://localhost:4318
#   resource:
#     attributes:
#       service.name: gateway-service
#   traces:
#     exporter: otlp
#   metrics:
#     exporter: otlp
#   logs:
#     exporter: otlp