server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
    gateway:
      discovery:
        locator:
          enabled: true # automatically map service names to routes
          lower-case-service-id: true